<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Nguyễn Văn An',
                'email' => 'nguyenvanan@gmail.com',
                'phone' => '0901234567',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar1.jpeg',
                'note' => 'Khách hàng thường xuyên tại khu vực Hà Nội.',
                'role_id' => 1,
                'status' => 'active',
            ],
            [
                'name' => 'Trần Thị Bích Ngọc',
                'email' => 'bichngoc@gmail.com',
                'phone' => '0912345678',
                'password' => Hash::make('password'),
                'gender' => 'female',
                'avatar' => 'avatar/avatar2.jpeg',
                'note' => 'Yêu thích các sản phẩm nội thất gỗ tự nhiên.',
                'role_id' => 1,
                'status' => 'active',
            ],
            [
                'name' => 'Lê Hoàng Dũng',
                'email' => 'hoangdung@gmail.com',
                'phone' => '0938765432',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar3.jpeg',
                'note' => 'Chuyên viên thiết kế nội thất.',
                'role_id' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Phạm Mai Linh',
                'email' => 'mailinh@gmail.com',
                'phone' => '0978543210',
                'password' => Hash::make('password'),
                'gender' => 'female',
                'avatar' => 'avatar/avatar4.jpeg',
                'note' => 'Khách hàng VIP tại TP.HCM.',
                'role_id' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Đặng Minh Tuấn',
                'email' => 'minhtuan@gmail.com',
                'phone' => '0922334455',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar5.jpeg',
                'note' => 'Thường đặt hàng vào dịp cuối năm.',
                'role_id' => 2,
                'status' => 'inactive',
            ],
            [
                'name' => 'Vũ Thanh Hằng',
                'email' => 'thanhhang@gmail.com',
                'phone' => '0933221144',
                'password' => Hash::make('password'),
                'gender' => 'female',
                'avatar' => 'avatar/avatar6.jpeg',
                'note' => 'Khách hàng thân thiết từ năm 2021.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Hoàng Nhật Nam',
                'email' => 'nhatnamhoang@gmail.com',
                'phone' => '0966112233',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar7.jpeg',
                'note' => 'Đã từng giới thiệu nhiều khách hàng mới.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Lương Thị Mỹ Duyên',
                'email' => 'myduyen@gmail.com',
                'phone' => '0909123456',
                'password' => Hash::make('password'),
                'gender' => 'female',
                'avatar' => 'avatar/avatar8.jpeg',
                'note' => 'Ưu tiên thanh toán bằng chuyển khoản.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Phan Hữu Khang',
                'email' => 'huukhang@gmail.com',
                'phone' => '0911223344',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar9.jpeg',
                'note' => 'Khách hàng doanh nghiệp.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Ngô Bảo Ngọc Trân',
                'email' => 'baotranngo@gmail.com',
                'phone' => '0944556678',
                'password' => Hash::make('password'),
                'gender' => 'female',
                'avatar' => 'avatar/avatar10.jpeg',
                'note' => 'Hay mua đồ trang trí cho văn phòng.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Lê Minh Quân',
                'email' => 'minhquan@gmail.com',
                'phone' => '0912345673',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar11.jpeg',
                'note' => 'Ưa thích phong cách tối giản, thường mua nội thất gỗ.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Trịnh Gia Hân',
                'email' => 'giahann@gmail.com',
                'phone' => '0934567890',
                'password' => Hash::make('password'),
                'gender' => 'female',
                'avatar' => 'avatar/avatar12.jpeg',
                'note' => 'Chuyên mua đồ decor nhà cửa vintage.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Vũ Thiên Long',
                'email' => 'thienlong@gmail.com',
                'phone' => '0978992233',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar13.jpeg',
                'note' => 'Hay đặt hàng bàn làm việc và ghế văn phòng.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Đặng Khánh Ngọc',
                'email' => 'khanhngoc@gmail.com',
                'phone' => '0922344556',
                'password' => Hash::make('password'),
                'gender' => 'female',
                'avatar' => 'avatar/avatar14.jpeg',
                'note' => 'Mua đồ cho căn hộ studio phong cách Hàn.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Trần Hoàng Dương',
                'email' => 'hoangduong@gmail.com',
                'phone' => '0967788990',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar15.jpeg',
                'note' => 'Khách quen chuyên đặt kệ sách và tủ bếp.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Lý Phương Linh',
                'email' => 'phuonglinh@gmail.com',
                'phone' => '0933225566',
                'password' => Hash::make('password'),
                'gender' => 'female',
                'avatar' => 'avatar/avatar16.jpeg',
                'note' => 'Thường xuyên mua nội thất phòng ngủ.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Nguyễn Nhật Nam',
                'email' => 'hoang@gmail.com',
                'phone' => '0988456677',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar17.jpeg',
                'note' => 'Mua combo bàn ăn + tủ trang trí.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Phan Thảo Nhi',
                'email' => 'thaonhi@gmail.com',
                'phone' => '0944899123',
                'password' => Hash::make('password'),
                'gender' => 'female',
                'avatar' => 'avatar/avatar18.jpeg',
                'note' => 'Phong cách hiện đại, thường mua đồ màu pastel.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Hồ Tuấn Kiệt',
                'email' => 'tuankiet@gmail.com',
                'phone' => '0977112233',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar19.jpeg',
                'note' => 'Khách hàng thân thiết, đặt hàng mỗi tháng.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Mai Thanh Hà',
                'email' => 'thanhha@gmail.com',
                'phone' => '0933445566',
                'password' => Hash::make('password'),
                'gender' => 'female',
                'avatar' => 'avatar/avatar20.jpeg',
                'note' => 'Hay chọn mua combo sofa + bàn trà.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Bùi Minh Khang',
                'email' => 'minhkhang@gmail.com',
                'phone' => '0967123489',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar21.jpeg',
                'note' => 'Thích sản phẩm gỗ tự nhiên, mộc mạc.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Tạ Ngọc Yến',
                'email' => 'ngocyen@gmail.com',
                'phone' => '0944001122',
                'password' => Hash::make('password'),
                'gender' => 'female',
                'avatar' => 'avatar/avatar22.jpeg',
                'note' => 'Khách hàng mới, vừa mua bàn học sinh.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Dương Anh Tú',
                'email' => 'anhtu@gmail.com',
                'phone' => '0977990066',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar23.jpeg',
                'note' => 'Khách doanh nghiệp, đặt nội thất văn phòng.',
                'role_id' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Dương Vũ Ngọc Quân',
                'email' => 'ngocquan@gmail.com',
                'phone' => '0977990046',
                'password' => Hash::make('password'),
                'gender' => 'male',
                'avatar' => 'avatar/avatar24.jpeg',
                'note' => 'Khách doanh nghiệp, đặt nội thất văn phòng.',
                'role_id' => 3,
                'status' => 'active',
            ],
        ];

        foreach ($users as &$user) {
            $user['email_verified_at'] = now();
            $user['created_at'] = $createdAt = Carbon::createFromTimestamp(mt_rand(Carbon::create(2020, 1, 1)->timestamp, Carbon::now()->timestamp));
            $user['updated_at'] = now();
        }

        DB::table('users')->insert($users);
    }
}
